// Mocks generated by Mockito 5.4.6 from annotations
// in arituki/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i11;

import 'package:arituki/models/event_supabase.dart' as _i6;
import 'package:arituki/providers/blocked_place_provider.dart' as _i10;
import 'package:arituki/providers/event_fetching_provider.dart' as _i7;
import 'package:arituki/providers/event_filter_provider.dart' as _i8;
import 'package:arituki/providers/event_sort_provider.dart' as _i12;
import 'package:arituki/providers/location_filter_provider.dart' as _i9;
import 'package:arituki/repositories/event_repository.dart' as _i4;
import 'package:arituki/services/analytics_service.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i2.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i3.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i4.EventRepository {
  MockEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get instanceId => (super.noSuchMethod(
        Invocation.getter(#instanceId),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#instanceId),
        ),
      ) as String);

  @override
  _i3.Future<List<_i6.EventoSupabase>> fetchEvents({
    required int? limit,
    required int? offset,
    DateTime? startDate,
    DateTime? endDate,
    String? city,
    String? province,
    String? selectedPlaceName,
    String? searchQuery,
    List<String>? excludedPlaces,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchEvents,
          [],
          {
            #limit: limit,
            #offset: offset,
            #startDate: startDate,
            #endDate: endDate,
            #city: city,
            #province: province,
            #selectedPlaceName: selectedPlaceName,
            #searchQuery: searchQuery,
            #excludedPlaces: excludedPlaces,
          },
        ),
        returnValue:
            _i3.Future<List<_i6.EventoSupabase>>.value(<_i6.EventoSupabase>[]),
      ) as _i3.Future<List<_i6.EventoSupabase>>);

  @override
  _i3.Future<int> getEventCount({
    DateTime? startDate,
    DateTime? endDate,
    String? city,
    String? province,
    String? selectedPlaceName,
    String? searchQuery,
    List<String>? excludedPlaces,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventCount,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #city: city,
            #province: province,
            #selectedPlaceName: selectedPlaceName,
            #searchQuery: searchQuery,
            #excludedPlaces: excludedPlaces,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i6.EventoSupabase>> fetchEventsByExactPlaceNames(
          List<String>? placeNames) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchEventsByExactPlaceNames,
          [placeNames],
        ),
        returnValue:
            _i3.Future<List<_i6.EventoSupabase>>.value(<_i6.EventoSupabase>[]),
      ) as _i3.Future<List<_i6.EventoSupabase>>);

  @override
  _i3.Future<List<_i6.EventoSupabase>> fetchEventsByTitle(String? title) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchEventsByTitle,
          [title],
        ),
        returnValue:
            _i3.Future<List<_i6.EventoSupabase>>.value(<_i6.EventoSupabase>[]),
      ) as _i3.Future<List<_i6.EventoSupabase>>);

  @override
  _i3.Future<List<_i6.EventoSupabase>> fetchEventsByIds(
          List<String>? eventIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchEventsByIds,
          [eventIds],
        ),
        returnValue:
            _i3.Future<List<_i6.EventoSupabase>>.value(<_i6.EventoSupabase>[]),
      ) as _i3.Future<List<_i6.EventoSupabase>>);

  @override
  _i3.Future<List<String>> getDistinctComunidades() => (super.noSuchMethod(
        Invocation.method(
          #getDistinctComunidades,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> getDistinctProvinces({String? comunidadName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDistinctProvinces,
          [],
          {#comunidadName: comunidadName},
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> getCitiesForProvince(String? provinceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCitiesForProvince,
          [provinceName],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);
}

/// A class which mocks [EventFetchingProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventFetchingProvider extends _i1.Mock
    implements _i7.EventFetchingProvider {
  MockEventFetchingProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.EventoSupabase> get allEvents => (super.noSuchMethod(
        Invocation.getter(#allEvents),
        returnValue: <_i6.EventoSupabase>[],
      ) as List<_i6.EventoSupabase>);

  @override
  bool get hasMoreEvents => (super.noSuchMethod(
        Invocation.getter(#hasMoreEvents),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingInitial => (super.noSuchMethod(
        Invocation.getter(#isLoadingInitial),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingMore => (super.noSuchMethod(
        Invocation.getter(#isLoadingMore),
        returnValue: false,
      ) as bool);

  @override
  int get totalDatabaseEventCount => (super.noSuchMethod(
        Invocation.getter(#totalDatabaseEventCount),
        returnValue: 0,
      ) as int);

  @override
  bool get isAnyEventLoaded => (super.noSuchMethod(
        Invocation.getter(#isAnyEventLoaded),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void updateDependencies(
    _i8.EventFilterProvider? fp,
    _i9.LocationFilterProvider? lfp,
    _i10.BlockedPlaceProvider? bpp,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDependencies,
          [
            fp,
            lfp,
            bpp,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> loadMoreEvents() => (super.noSuchMethod(
        Invocation.method(
          #loadMoreEvents,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> refreshEvents() => (super.noSuchMethod(
        Invocation.method(
          #refreshEvents,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EventFilterProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventFilterProvider extends _i1.Mock
    implements _i8.EventFilterProvider {
  MockEventFilterProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.EventFilterState get filterState => (super.noSuchMethod(
        Invocation.getter(#filterState),
        returnValue: _i8.EventFilterState.all,
      ) as _i8.EventFilterState);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  bool get isAnyFilterActive => (super.noSuchMethod(
        Invocation.getter(#isAnyFilterActive),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setFilterState(_i8.EventFilterState? state) => super.noSuchMethod(
        Invocation.method(
          #setFilterState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #updateSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDateFilter(
    String? dateFilterValue, {
    bool? notify = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDateFilter,
          [dateFilterValue],
          {#notify: notify},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePlaceFilter(
    String? placeFilterValue, {
    bool? notify = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updatePlaceFilter,
          [placeFilterValue],
          {#notify: notify},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetAllFilters() => super.noSuchMethod(
        Invocation.method(
          #resetAllFilters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i6.EventoSupabase> applyFilters(
    List<_i6.EventoSupabase>? events, {
    bool? ignoreDateFilter = false,
    bool? ignorePlaceFilter = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyFilters,
          [events],
          {
            #ignoreDateFilter: ignoreDateFilter,
            #ignorePlaceFilter: ignorePlaceFilter,
          },
        ),
        returnValue: <_i6.EventoSupabase>[],
      ) as List<_i6.EventoSupabase>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EventSortProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventSortProvider extends _i1.Mock implements _i12.EventSortProvider {
  MockEventSortProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.EventSortCriteria get currentSortCriteria => (super.noSuchMethod(
        Invocation.getter(#currentSortCriteria),
        returnValue: _i12.EventSortCriteria.date,
      ) as _i12.EventSortCriteria);

  @override
  bool get isAscending => (super.noSuchMethod(
        Invocation.getter(#isAscending),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setSortOrder(
    _i12.EventSortCriteria? criteria,
    bool? ascending,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSortOrder,
          [
            criteria,
            ascending,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i6.EventoSupabase> sortEvents(List<_i6.EventoSupabase>? events) =>
      (super.noSuchMethod(
        Invocation.method(
          #sortEvents,
          [events],
        ),
        returnValue: <_i6.EventoSupabase>[],
      ) as List<_i6.EventoSupabase>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocationFilterProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationFilterProvider extends _i1.Mock
    implements _i9.LocationFilterProvider {
  MockLocationFilterProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
      ) as bool);

  @override
  List<String> get comunidades => (super.noSuchMethod(
        Invocation.getter(#comunidades),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get isLoadingComunidades => (super.noSuchMethod(
        Invocation.getter(#isLoadingComunidades),
        returnValue: false,
      ) as bool);

  @override
  List<String> get provinces => (super.noSuchMethod(
        Invocation.getter(#provinces),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get isLoadingProvinces => (super.noSuchMethod(
        Invocation.getter(#isLoadingProvinces),
        returnValue: false,
      ) as bool);

  @override
  List<String> get availableCitiesForProvince => (super.noSuchMethod(
        Invocation.getter(#availableCitiesForProvince),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get selectedEventCities => (super.noSuchMethod(
        Invocation.getter(#selectedEventCities),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get isLoadingCities => (super.noSuchMethod(
        Invocation.getter(#isLoadingCities),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> loadComunidades() => (super.noSuchMethod(
        Invocation.method(
          #loadComunidades,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> selectComunidad(String? comunidad) => (super.noSuchMethod(
        Invocation.method(
          #selectComunidad,
          [comunidad],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadProvinces({required bool? fromUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadProvinces,
          [],
          {#fromUser: fromUser},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> selectProvince(String? province) => (super.noSuchMethod(
        Invocation.method(
          #selectProvince,
          [province],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadCities({required bool? fromUser}) => (super.noSuchMethod(
        Invocation.method(
          #loadCities,
          [],
          {#fromUser: fromUser},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void setSelectedCities(List<String>? cities) => super.noSuchMethod(
        Invocation.method(
          #setSelectedCities,
          [cities],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectAppBarCity(String? city) => super.noSuchMethod(
        Invocation.method(
          #selectAppBarCity,
          [city],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllFiltersAndPreferences() => (super.noSuchMethod(
        Invocation.method(
          #clearAllFiltersAndPreferences,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i13.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> logScreenView(String? screenName) => (super.noSuchMethod(
        Invocation.method(
          #logScreenView,
          [screenName],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logBottomNavBarTapped({required String? itemName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #logBottomNavBarTapped,
          [],
          {#itemName: itemName},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logEventDetailView({
    required String? eventName,
    String? placeName,
    String? cityName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logEventDetailView,
          [],
          {
            #eventName: eventName,
            #placeName: placeName,
            #cityName: cityName,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logProgramaDetailView({required String? programaName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #logProgramaDetailView,
          [],
          {#programaName: programaName},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logGastroDetailView({required String? jornadaName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #logGastroDetailView,
          [],
          {#jornadaName: jornadaName},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logGastroProgramaView({required String? programaName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #logGastroProgramaView,
          [],
          {#programaName: programaName},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logEventLinkClick({
    required String? eventName,
    required String? linkType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logEventLinkClick,
          [],
          {
            #eventName: eventName,
            #linkType: linkType,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logProgramaLinkClick({
    required String? programaName,
    required String? linkType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logProgramaLinkClick,
          [],
          {
            #programaName: programaName,
            #linkType: linkType,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logCineTicketLinkClick({
    required String? movieTitle,
    required String? cinemaName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logCineTicketLinkClick,
          [],
          {
            #movieTitle: movieTitle,
            #cinemaName: cinemaName,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logGastroLinkClick({
    required String? jornadaName,
    required String? linkType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logGastroLinkClick,
          [],
          {
            #jornadaName: jornadaName,
            #linkType: linkType,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logEventFavoriteToggle({
    required String? eventName,
    required bool? isFavorite,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logEventFavoriteToggle,
          [],
          {
            #eventName: eventName,
            #isFavorite: isFavorite,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logPlaceFavoriteToggle({
    required String? placeName,
    required bool? isFavorite,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logPlaceFavoriteToggle,
          [],
          {
            #placeName: placeName,
            #isFavorite: isFavorite,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logEventBlockToggle({
    required String? eventName,
    required bool? isBlocked,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logEventBlockToggle,
          [],
          {
            #eventName: eventName,
            #isBlocked: isBlocked,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logPlaceBlockToggle({
    required String? placeName,
    required bool? isBlocked,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logPlaceBlockToggle,
          [],
          {
            #placeName: placeName,
            #isBlocked: isBlocked,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logEventInteraction({
    required String? eventName,
    required String? interaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logEventInteraction,
          [],
          {
            #eventName: eventName,
            #interaction: interaction,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logSearch({required String? searchTerm}) =>
      (super.noSuchMethod(
        Invocation.method(
          #logSearch,
          [],
          {#searchTerm: searchTerm},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logFilterChange({
    required String? filterType,
    required String? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logFilterChange,
          [],
          {
            #filterType: filterType,
            #value: value,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logLocationFilterChange({
    required String? filterType,
    String? comunidad,
    String? province,
    List<String>? cities,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logLocationFilterChange,
          [],
          {
            #filterType: filterType,
            #comunidad: comunidad,
            #province: province,
            #cities: cities,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
