// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWnid8nfH8TS78tMn62xe-MCOX1YtkzBQ',
    appId: '1:949702547598:web:b88cb7f56be5d815e0d1df',
    messagingSenderId: '949702547598',
    projectId: 'zgzapp-91c27',
    authDomain: 'zgzapp-91c27.firebaseapp.com',
    storageBucket: 'zgzapp-91c27.firebasestorage.app',
    measurementId: 'G-QCMFH0D7MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmDGdHTyhQtHKx0AwS6pug4dmyYPDY-uE',
    appId: '1:949702547598:android:0b37ad0539a62915e0d1df',
    messagingSenderId: '949702547598',
    projectId: 'zgzapp-91c27',
    storageBucket: 'zgzapp-91c27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk17SOjASFGLBw5m3O2_DWHeKLAgiEo6w',
    appId: '1:949702547598:ios:080123990e9aa5abe0d1df',
    messagingSenderId: '949702547598',
    projectId: 'zgzapp-91c27',
    storageBucket: 'zgzapp-91c27.firebasestorage.app',
    iosBundleId: 'com.example.zgzapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWnid8nfH8TS78tMn62xe-MCOX1YtkzBQ',
    appId: '1:949702547598:web:edcca9111dc84401e0d1df',
    messagingSenderId: '949702547598',
    projectId: 'zgzapp-91c27',
    authDomain: 'zgzapp-91c27.firebaseapp.com',
    storageBucket: 'zgzapp-91c27.firebasestorage.app',
    measurementId: 'G-N2E1PL5RYB',
  );
}
